version: '2.1'
# networks:
  # graph:
    # driver: bridge

services:
  redis:
    image: redis
    container_name: graph-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  neo4j:
    image: neo4j
    container_name: graph-neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: curl --fail http://localhost:7474 || exit 1
      retries: 5

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: graph-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  parser:
    build: ./parser
    image: graph:parser
    container_name: graph-parser
    depends_on:
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
    links:
      - redis
      - rabbit
    restart: always

  reprocessor:
    build: ./reprocessor
    image: graph:reprocessor
    container_name: graph-reprocessor
    depends_on:
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
    links:
      - redis
      - rabbit

  graph-saver:
    build: ./graph-saver
    image: graph:saver
    container_name: graph-saver
    depends_on:
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
      parser:
        condition: service_started
    links:
      - redis
      - neo4j
      - rabbit
    restart: always